import type { EventCategory, EventItem, User } from "./types";

export const ADMIN_PASSWORD = "JG Link 2";

export const APP_NAME = "JG EVENT MANAGER";

export const COUNTRY_CODES: { name: string; code: string; flag: string }[] = [
  { name: "United States", code: "+1", flag: "🇺🇸" },
  { name: "United Kingdom", code: "+44", flag: "🇬🇧" },
  { name: "Canada", code: "+1", flag: "🇨🇦" },
  { name: "Australia", code: "+61", flag: "🇦🇺" },
  { name: "Nigeria", code: "+234", flag: "🇳🇬" },
  { name: "Ghana", code: "+233", flag: "🇬🇭" },
  { name: "Kenya", code: "+254", flag: "🇰🇪" },
  { name: "South Africa", code: "+27", flag: "🇿🇦" },
  { name: "India", code: "+91", flag: "🇮🇳" },
  { name: "France", code: "+33", flag: "🇫🇷" },
  { name: "Germany", code: "+49", flag: "🇩🇪" },
  { name: "Brazil", code: "+55", flag: "🇧🇷" },
  { name: "Mexico", code: "+52", flag: "🇲🇽" },
  { name: "Japan", code: "+81", flag: "🇯🇵" },
  { name: "China", code: "+86", flag: "🇨🇳" },
  { name: "Italy", code: "+39", flag: "🇮🇹" },
  { name: "Spain", code: "+34", flag: "🇪🇸" },
  { name: "Netherlands", code: "+31", flag: "🇳🇱" },
  { name: "Switzerland", code: "+41", flag: "🇨🇭" },
  { name: "Sweden", code: "+46", flag: "🇸🇪" },
  { name: "Norway", code: "+47", flag: "🇳🇴" },
  { name: "Denmark", code: "+45", flag: "🇩🇰" },
  { name: "Finland", code: "+358", flag: "🇫🇮" },
  { name: "Belgium", code: "+32", flag: "🇧🇪" },
  { name: "Portugal", code: "+351", flag: "🇵🇹" },
  { name: "Ireland", code: "+353", flag: "🇮🇪" },
  { name: "Poland", code: "+48", flag: "🇵🇱" },
  { name: "Russia", code: "+7", flag: "🇷🇺" },
  { name: "Turkey", code: "+90", flag: "🇹🇷" },
  { name: "Egypt", code: "+20", flag: "🇪🇬" },
  { name: "Morocco", code: "+212", flag: "🇲🇦" },
  { name: "Tanzania", code: "+255", flag: "🇹🇿" },
  { name: "Uganda", code: "+256", flag: "🇺🇬" },
  { name: "Ethiopia", code: "+251", flag: "🇪🇹" },
  { name: "Zimbabwe", code: "+263", flag: "🇿🇼" },
  { name: "Zambia", code: "+260", flag: "🇿🇲" },
  { name: "Cameroon", code: "+237", flag: "🇨🇲" },
  { name: "Senegal", code: "+221", flag: "🇸🇳" },
  { name: "Rwanda", code: "+250", flag: "🇷🇼" },
  { name: "Saudi Arabia", code: "+966", flag: "🇸🇦" },
  { name: "UAE", code: "+971", flag: "🇦🇪" },
  { name: "Singapore", code: "+65", flag: "🇸🇬" },
  { name: "Malaysia", code: "+60", flag: "🇲🇾" },
  { name: "Philippines", code: "+63", flag: "🇵🇭" },
  { name: "Pakistan", code: "+92", flag: "🇵🇰" },
  { name: "Bangladesh", code: "+880", flag: "🇧🇩" },
  { name: "Argentina", code: "+54", flag: "🇦🇷" },
  { name: "Colombia", code: "+57", flag: "🇨🇴" },
  { name: "Chile", code: "+56", flag: "🇨🇱" },
  { name: "Peru", code: "+51", flag: "🇵🇪" },
];

export const CATEGORIES: {
  value: EventCategory;
  label: string;
  icon: string;
  color: string;
  bgColor: string;
}[] = [
  { value: "Wedding", label: "Wedding", icon: "Heart", color: "text-rose-600", bgColor: "bg-rose-100" },
  { value: "Funeral", label: "Funeral", icon: "Heart", color: "text-slate-600", bgColor: "bg-slate-100" },
  { value: "Birthday", label: "Birthday", icon: "Cake", color: "text-amber-600", bgColor: "bg-amber-100" },
  { value: "Party", label: "Party", icon: "Music", color: "text-cyan-600", bgColor: "bg-cyan-100" },
  { value: "Meeting", label: "Meeting", icon: "Briefcase", color: "text-emerald-600", bgColor: "bg-emerald-100" },
  { value: "Memorial", label: "Memorial", icon: "Heart", color: "text-violet-600", bgColor: "bg-violet-100" },
  { value: "Graduation", label: "Graduation", icon: "GraduationCap", color: "text-indigo-600", bgColor: "bg-indigo-100" },
  { value: "Charity", label: "Charity", icon: "HeartHandshake", color: "text-teal-600", bgColor: "bg-teal-100" },
  { value: "Fundraiser", label: "Fundraiser", icon: "Gift", color: "text-orange-600", bgColor: "bg-orange-100" },
  { value: "Anniversary", label: "Anniversary", icon: "Sparkles", color: "text-pink-600", bgColor: "bg-pink-100" },
  { value: "Other", label: "Other", icon: "Calendar", color: "text-gray-600", bgColor: "bg-gray-100" },
];

export const SEED_EVENTS: EventItem[] = [
  {
    id: "evt-001",
    title: "Sarah & James Wedding",
    category: "Wedding",
    description: "Join us in celebrating the union of Sarah and James. Help us make this day unforgettable!",
    targetAmount: 15000,
    suggestedContribution: 150,
    targetDate: "2025-12-15",
    location: "Grand Cathedral Hall, New York",
    adminPhone: "+1 (555) 123-4567",
    adminAccountName: "James Wedding Fund",
    adminAccountDetails: "Bank of America - Account #: 9876543210, Routing: 021000021",
    status: "Active",
    createdBy: "admin-001",
    createdAt: "2025-01-15T10:00:00Z",
    contributors: ["user-001", "user-002"],
    totalCollected: 3200,
  },
  {
    id: "evt-002",
    title: "Grandma Rose Memorial Service",
    category: "Funeral",
    description: "Support for the funeral arrangements of our beloved Grandmother Rose.",
    targetAmount: 8000,
    suggestedContribution: 100,
    targetDate: "2025-03-10",
    location: "St. Mary's Church, Chicago",
    adminPhone: "+1 (555) 234-5678",
    adminAccountName: "Rose Memorial Fund",
    adminAccountDetails: "Chase Bank - Account #: 8765432109, Routing: 021000021",
    status: "Urgent",
    createdBy: "admin-001",
    createdAt: "2025-02-01T08:00:00Z",
    contributors: ["user-003"],
    totalCollected: 1200,
  },
  {
    id: "evt-003",
    title: "Alex's 30th Birthday Bash",
    category: "Birthday",
    description: "Let's throw an amazing 30th birthday party for Alex!",
    targetAmount: 3000,
    suggestedContribution: 50,
    targetDate: "2025-06-20",
    location: "Skyline Rooftop, Los Angeles",
    adminPhone: "+1 (555) 345-6789",
    adminAccountName: "Alex Birthday Fund",
    adminAccountDetails: "Wells Fargo - Account #: 7654321098, Routing: 121000248",
    status: "Active",
    createdBy: "admin-001",
    createdAt: "2025-03-01T12:00:00Z",
    contributors: [],
    totalCollected: 0,
  },
  {
    id: "evt-004",
    title: "Community Quarterly Meeting",
    category: "Meeting",
    description: "Quarterly community outreach and planning meeting for the neighborhood association.",
    targetAmount: 500,
    suggestedContribution: 25,
    targetDate: "2025-04-05",
    location: "Community Center, Houston",
    adminPhone: "+1 (555) 456-7890",
    adminAccountName: "Community Fund",
    adminAccountDetails: "CashApp: $CommunityFund",
    status: "Upcoming",
    createdBy: "admin-001",
    createdAt: "2025-03-10T09:00:00Z",
    contributors: [],
    totalCollected: 0,
  },
  {
    id: "evt-005",
    title: "End of Year Office Party",
    category: "Party",
    description: "Celebrating a fantastic year together! Food, drinks, and entertainment.",
    targetAmount: 5000,
    suggestedContribution: 75,
    targetDate: "2025-12-28",
    location: "The Grand Ballroom, Miami",
    adminPhone: "+1 (555) 567-8901",
    adminAccountName: "Office Party Fund",
    adminAccountDetails: "Venmo: @OfficeParty2025",
    status: "Active",
    createdBy: "admin-001",
    createdAt: "2025-03-15T14:00:00Z",
    contributors: [],
    totalCollected: 0,
  },
  {
    id: "evt-006",
    title: "Mark's Graduation Celebration",
    category: "Graduation",
    description: "Help us celebrate Mark's graduation with a memorable party!",
    targetAmount: 2500,
    suggestedContribution: 40,
    targetDate: "2025-05-10",
    location: "University Gardens, Boston",
    adminPhone: "+1 (555) 678-9012",
    adminAccountName: "Mark Grad Fund",
    adminAccountDetails: "PayPal: mark.grad@email.com",
    status: "Completed",
    createdBy: "admin-001",
    createdAt: "2025-02-20T11:00:00Z",
    contributors: ["user-001", "user-002", "user-003"],
    totalCollected: 2800,
  },
  {
    id: "evt-007",
    title: "School Supplies Drive",
    category: "Charity",
    description: "Gathering funds to provide school supplies for underprivileged children.",
    targetAmount: 10000,
    suggestedContribution: 50,
    targetDate: "2025-08-20",
    location: "Various Schools, Atlanta",
    adminPhone: "+1 (555) 789-0123",
    adminAccountName: "School Drive Fund",
    adminAccountDetails: "Bank of America - Account #: 6543210987, Routing: 021000021",
    status: "Active",
    createdBy: "admin-001",
    createdAt: "2025-04-01T07:00:00Z",
    contributors: [],
    totalCollected: 0,
  },
];

export const SEED_USERS: User[] = [
  {
    id: "user-001",
    name: "John Doe",
    email: "john@example.com",
    country: "United States",
    mobile: "+1 (555) 111-2222",
    password: "John1234",
    profilePicture: "",
    role: "user",
    blocked: false,
    createdAt: "2025-01-01T10:00:00Z",
  },
  {
    id: "user-002",
    name: "Jane Smith",
    email: "jane@example.com",
    country: "Canada",
    mobile: "+1 (555) 222-3333",
    password: "Jane5678",
    profilePicture: "",
    role: "user",
    blocked: false,
    createdAt: "2025-01-02T10:00:00Z",
  },
  {
    id: "user-003",
    name: "Bob Johnson",
    email: "bob@example.com",
    country: "United Kingdom",
    mobile: "+44 7700 900123",
    password: "Bob9012",
    profilePicture: "",
    role: "user",
    blocked: false,
    createdAt: "2025-01-03T10:00:00Z",
  },
  {
    id: "admin-001",
    name: "JG Admin",
    email: "admin@jgeventmanager.com",
    country: "United States",
    mobile: "+1 (555) 000-0001",
    password: "Admin2025!",
    profilePicture: "",
    role: "admin",
    blocked: false,
    createdAt: "2025-01-01T00:00:00Z",
  },
];

export const AVATAR_PRESETS = [
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Felix",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Aneka",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Salem",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Mia",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Leo",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Zoe",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Jack",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Luna",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Oscar",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Lily",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Max",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Aria",
];

export const CATEGORY_WATERMARK_COLORS: Record<EventCategory, string> = {
  Wedding: "#e11d48",
  Funeral: "#475569",
  Birthday: "#d97706",
  Party: "#06b6d4",
  Meeting: "#059669",
  Memorial: "#7c3aed",
  Graduation: "#4f46e5",
  Charity: "#0d9488",
  Fundraiser: "#ea580c",
  Anniversary: "#db2777",
  Other: "#6b7280",
};